### ISSUE TITLE
Multiple Terra Address support in Ledger

### ISSUE THREAD

**Issue by kickthedragon** [terra-money/station-extension#1]
Feature Request:

Currently the Terra Station Extension doesn't support multiple addresses when using Ledger.  This would be very helpful when trying to manage multiple accounts using the same ledger device.  This is doable with most other currencies on ledger (Bitcoin, ETH, XLM, etc.). 

Based on a Ledger support case it seems to be it is doable but just needs to be implemented on the Station Extension 

(Ref: https://www.reddit.com/r/terraluna/comments/q28ioy/can_you_have_multiple_ledger_addresses_on_terra)

It would be great if we could do this similar to how MetaMask allows us to add multiple ETH Ledger Addresses and label them.

**Comment by simcheolhwan** [comment]
Ledger index feature will be supported soon.

**Comment by simcheolhwan** [comment]
b4dbabd closes this

**Comment by kickthedragon** [comment]
Awesome thank you so much! That was so fast!
