### ISSUE TITLE
Hiding small balances doesn't work properly

### ISSUE THREAD

**Issue by sriedel1970** [terra-money/station-extension#10]
The feature to hide away coins/ tokens with small balances doesn't work correctly, at least for me (MacOS, Brave browser, Terra Station browser extension connected to a Ledger Nano X, all running on latest SW versions). No matter what setting I choose (Show all, Hide <$1, Hide <$10, Hide <$100), basically all symbols are still shown in my wallet. The only effect seems to be that the order of the symbols is somehow affected, strangely.

As you can see in the following image, despite the current setting to hide away balances of less than $10, nothing is hidden away. Both symbols with a flat zero and those with small fractions of a token are still displayed. This feature is obviously not working correctly.

![image](https://user-images.githubusercontent.com/93739130/165078673-6d02f140-0e56-4cd7-bb23-81ec2890221c.png)

**Comment by simcheolhwan** [comment]
It does not apply to custom tokens. Because for a few reasons, it's not loading the price of all those tokens. First of all, it cannot be confirmed that all tokens have a UST pair, and the size of the pool may be different for each dex.

**Comment by sriedel1970** [comment]
@[simcheolhwan], thanks for replying. Although I do not agree to close this issue that fast. I understand that there are reasons that _some_ of the tokens shouldn't be hidden away in the circumstances you mentioned. But what about all the tokens with a flat out zero ("0" without even a decimal point) that currently persist to be shown (see my screenshot), those should be hidden, don't you agree? 

And if not, what is the point of the whole "Hide small balances" feature at all -- it is to hide away the dust, and for use not only LUNA and UST, don't you think?
