### ISSUE TITLE
No way to whitelist domains

### ISSUE THREAD

**Issue by ExtraHash** [terra-money/station-extension#12]
When browsing legitimate websites with one of the keywords added in the last commit, a constant alert is popped up on every page load and there is no way to whitelist a domain name to prevent this from happening. This makes the website very painful to use. Please consider adding an add to whitelist feature

**Comment by austinginder** [comment]
Likewise would like to whitelist my own website https://anchor.host. I run a WordPress web hosting service called Anchor Hosting. One of my colleagues just reported this issue when they view my website.

![Screen Shot 2022-04-26 at 12 28 54 PM](https://user-images.githubusercontent.com/110346/165359919-30ad5a94-db0d-4a40-a0ed-7ad6ccd079ae.png)

**Comment by simcheolhwan** [comment]
I understand what you're saying. It's actually an expected side effect, but I haven't prevented it enough. Nevertheless, there are already too many scams sites, so we rushed to release this feature. It's going to be improved.
