### ISSUE TITLE
Hiding small balances doesn't work properly, continued

### ISSUE THREAD

**Issue by sriedel1970** [terra-money/station-extension#13]
Sorry for creating another issue on that, but I don't know how to reopen the existing issue that has been closed without any chance for me to reply first. On top of that, I left a comment in the original issue that received no reply, so I presume there was no notification because the issue was closed. 

Please forgive me for acting stupid, but I am not a frequent Github user :P

vvv my last comment from the original issue below vvv

@simcheolhwan, thanks for replying. Although I do not agree to close this issue that fast. I understand that there are reasons that _some_ of the tokens shouldn't be hidden away in the circumstances you mentioned. But what about all the tokens with a flat out zero ("0" without even a decimal point) that currently persist to be shown (see my screenshot), those should be hidden, don't you agree? 

And if not, what is the point of the whole "Hide small balances" feature at all -- it is to hide away the dust, and for sure not only LUNA and UST, don't you think?

_Originally posted by @sriedel1970 in https://github.com/terra-money/station-extension/issues/10#issuecomment-1111048147_

**Comment by simcheolhwan** [comment]
I agree that if the value is 0, it would be reasonable to be hidden.
