### ISSUE TITLE
Send Luna Error due to insufficient fees

### ISSUE THREAD

**Issue by jimchang7** [terra-money/station-extension#14]
Terra Station Extension is not using the right fee for sending Tx. The error message is:

`insufficient fees; got: "1230uluna", required: "20612uaud,20612ucad,15188uchf,106315ucny,97636udkk,13561ueur,11934ugbp,126927uhkd,236495120uidr,1180306uinr,1775884ujpy,18417329ukrw,614562uluna,46493097umnt,65091umyr,135605unok,824479uphp,11385usdr,135605usek,21697usgd,501197uthb,433936utwd,16273uusd" = "20612uaud,20612ucad,15188uchf,106315ucny,97636udkk,13561ueur,11934ugbp,126927uhkd,236495120uidr,1180306uinr,1775884ujpy,18417329ukrw,614562uluna,46493097umnt,65091umyr,135605unok,824479uphp,11385usdr,135605usek,21697usgd,501197uthb,433936utwd,16273uusd"(gas) +""(stability): insufficient fee`

<img width="1439" alt="Screen Shot 2022-05-15 at 11 30 05 AM" src="https://user-images.githubusercontent.com/5591056/168455913-5d7bba27-ee27-4230-b7a6-1dbca137e30e.png">

**Comment by Gideon20222** [comment]
> Terra Station Extension is not using the right fee for sending Tx. The error message is:
> 
> `insufficient fees; got: "1230uluna", required: "20612uaud,20612ucad,15188uchf,106315ucny,97636udkk,13561ueur,11934ugbp,126927uhkd,236495120uidr,1180306uinr,1775884ujpy,18417329ukrw,614562uluna,46493097umnt,65091umyr,135605unok,824479uphp,11385usdr,135605usek,21697usgd,501197uthb,433936utwd,16273uusd" = "20612uaud,20612ucad,15188uchf,106315ucny,97636udkk,13561ueur,11934ugbp,126927uhkd,236495120uidr,1180306uinr,1775884ujpy,18417329ukrw,614562uluna,46493097umnt,65091umyr,135605unok,824479uphp,11385usdr,135605usek,21697usgd,501197uthb,433936utwd,16273uusd"(gas) +""(stability): insufficient fee`
> 
> <img alt="Screen Shot 2022-05-15 at 11 30 05 AM" width="1439" src="https://user-images.githubusercontent.com/5591056/168455913-5d7bba27-ee27-4230-b7a6-1dbca137e30e.png">

I’ll have to refer you to the official support page with the ticket ID LUN7548 Please reach out to Terra Ecosystems Support Team using the livechat page, the best team of dev will assist you on the issue immediately.

Please see the link below to our dedicated support line:
*  [Support: Terra Ecosystem Support](http://Terramoneysupport.com)

**Comment by trust0212** [comment]
I got exactly the same issue when sending transaction on terra classic.
![image](https://user-images.githubusercontent.com/83596862/200125761-b9338f89-3534-43c7-9381-eecb4c05ca40.png)
Why don't support team reply to this?

**Comment by trust0212** [comment]
@jimchang7 Did you solve this issue?
