### ISSUE TITLE
Connecting Ledger over Bluetooth - Blank screen

### ISSUE THREAD

**Issue by 0xphilipp** [terra-money/station-extension#164]
![image](https://github.com/terra-money/station-extension/assets/9350951/333ea203-5f98-4110-b361-a91fa9e24ad4)
![image](https://github.com/terra-money/station-extension/assets/9350951/d3c29a6b-90a5-4038-8889-8b83e29bff52)

**Comment by 0xphilipp** [comment]
After browser restart, the wallet is shown

**Comment by 0xphilipp** [comment]
But broadcast / posting it never reaches the ledger. Post immediately returns to the dApp and does not send sign message to the ledger.

**Comment by Patjalee** [comment]
> ![ภาพ](https://user-images.githubusercontent.com/9350951/241391652-333ea203-5f98-4110-b361-a91fa9e24ad4.png) ![ภาพ](https://user-images.githubusercontent.com/9350951/241391679-d3c29a6b-90a5-4038-8889-8b83e29bff52.png)

```

```
