### ISSUE TITLE
Issue with states() and connectedWallet() observables not triggering

### ISSUE THREAD

**Issue by 0xphilipp** [terra-money/station-extension#27]
Hi, I'm Philipp from Eris Protocol,

currently we have issues with the state observables of @terra-money/wallet-controller to terra station extension.

The flow is the following:
- Open erisprotocol, connect your wallet
- Leave erisprotocol somewhere in the background for 5 - 60 min
- Disconnect the wallet within the app: 
![image](https://user-images.githubusercontent.com/9350951/195555979-e4334afb-3fe2-4680-86a6-baf4bdee7e01.png)
- Press connect wallet again
![image](https://user-images.githubusercontent.com/9350951/195556037-88fb1ff2-1c50-4d7d-a07d-046265261a12.png)
- Connect the station again
- Now our gui does not update, as we do not receive the wallet connected state again.

The user needs to refresh the page, so that it works again, and with the refresh of the page, the wallet magically appears, so the wallet is internally connected, but the observable not triggered. I do not know if this is a @terra-money/wallet-controller issue or a Terra Station issue.

We tried some workarounds of recreating the WalletInstance or resubscribing the state (reexecute initInstance / reinitSubscription). Unfortunately these workarounds never worked, as e.g. when recreating the wallet instance after that long time, we will only receive the INITIALIZING state and nothing more.

On startup we call
```
  private async initInstance(waitOnAvailable = false) {
    this.subscriptions.clear();
    const chainOptions = await getChainOptions();
    this.instance = new WalletController({
      ...chainOptions,
    });

    this.isAvailable = true;

    if (waitOnAvailable) {
      await firstValueFrom(
        this.instance.states().pipe(
          tap((a) => console.log('STATE', a)),
          filter((a) => a.status !== WalletStatus.INITIALIZING)
        )
      );
      console.log('WAITED');
    }

    this.reinitSubscription();
  }

  private reinitSubscription() {
    this.subscriptions.clear();
    this.subscriptions.add = this.instance
      .connectedWallet()
      .subscribe((wallet) => {
        this.connectedWallet.next(wallet);
        this.address.next(wallet?.terraAddress.toString() ?? '');
      });
  }
```

On connect we call
```
    await this.instance?.connect(connection.type, connection.identifier);
```

On disconnect we call
```
    this.instance?.disconnect();
```

**Comment by alecande11** [comment]
Do you still have this issue?

**Comment by ericHgorski** [comment]
Should be fixed in recent change. Please re-open if not.
