### ISSUE TITLE
Account Sequence Mismatch

### ISSUE THREAD

**Issue by DemonRx** [terra-money/station-extension#30]
![image](https://user-images.githubusercontent.com/18432686/198871909-cb8d2e3d-1fe8-42ec-83c3-5630860e81a6.png)

**Comment by alecande11** [comment]
It was probably a temporary problem since it works for me now.

**Comment by DemonRx** [comment]
I still have this occurring. Multiple times infact just these last couple days while providing liquidity to some pools on astroport. As well as when I was swapping.

**Comment by DemonRx** [comment]
So I end up having to retry posting the transaction. Is it known why this might be occuring ?

**Comment by alecande11** [comment]
You are probably signing the second tx before the first one is confirmed onchain.

**Comment by DemonRx** [comment]
So to be clear as to the steps I've been performing ...

1. Select amount of tokens from my wallet to be added to the pool 
2. Click on provide 
3. Dialogue window shows asking to confirm adding the tokens
4. Station extension opens and I type in my password 
5. I click on post
6. The website shows "pending"
7. Notification appears saying it fails

What second transaction are you referring to based on the steps I just outlined ? Before I do anything further on the platforms I always wait to see a confirmation notification.
