### ISSUE TITLE
Wrong Insufficient error on classic

### ISSUE THREAD

**Issue by trust0212** [terra-money/station-extension#31]
I have got error message when I tried to call contract function using terra station extension.
Even I have enough lunc and ust in my wallet, insufficient error.
![image](https://user-images.githubusercontent.com/83596862/200126470-42de7b02-048d-4c49-935d-9c595b1e7d58.png)

Hope to solve this asap.
Thanks

**Comment by agrant-1** [comment]
Trying

**Comment by alecande11** [comment]
Classic only.
