### ISSUE TITLE
LocalTerra issue with station-extension

### ISSUE THREAD

**Issue by luncbae** [terra-money/station-extension#33]
When using the wallet extension with LocalTerra this error is displayed in console:

http://localhost:1317/cosmos/bank/v1beta1/spendable_balances/terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v 501 (Not Implemented) 

I was able to compile the station-extension and test modifying the src/data/queryies/bank.ts line 53:

old: const [coins] = await lcd.bank.spendableBalances(address)
new: const [coins] = await lcd.bank.balance(address)

this resolved the issue but i am unable to create a pull request.

**Comment by alecande11** [comment]
You are probably not using the latest LocalTerra version.
