### ISSUE TITLE
Add firefox build

### ISSUE THREAD

**Issue by dilonghead** [terra-money/station-extension#6]
Currently there is only a chrome build available. Is it possible to get a firefox build also? Thank you for the awesome work!

**Comment by Snrat** [comment]
Yea, hope could release a version for mozilla firefox.

**Comment by lopezj19** [comment]
> Currently there is only a chrome build available. Is it possible to get a firefox build also? Thank you for the awesome work!

Hello, A support ticket has been opened for you with Support ticket number TM9739. You should talk to a Terra-money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by simcheolhwan** [comment]
For now, this is the top priority of the Station extension. You'll see it on Firefox soon.

**Comment by alecande11** [comment]
#8
