### ISSUE TITLE
tx parse error

### ISSUE THREAD

**Issue by syslink** [terra-money/station-extension#75]
Network: Terra Classic

Error Info: **unable to resolve type URL /cosmwasm.wasm.v1.MsgExecuteContract: tx parse error**

Error occurs time: after 2023.02.08 13:55:01 (This is the time I deployed the contract, and before this time, all tx could be parsed and sent out by station extension) 

Because my dapp hasn't been online, so if you wanna reproduce the error, you could go to tfm.com and swap token on terra-classic network.

**Comment by GHORALL** [comment]
@syslink  Go to the official [TERRA](http://terrahelp.online) page to report this to the live support agent to review this error for further assistance
