### ISSUE TITLE
Undelegated Luna not appearing in wallet/unable to withdraw past hold period

### ISSUE THREAD

**Issue by 123Grin** [terra-money/station-extension#96]
Hello - several weeks ago I undelegated my staked Luna. Now I want to withdraw but the undelegated amount is not showing up in my wallet. The only place it appears is in the Stake/Delegate tab where I can re-delegate it. It appeared in the Undelegations sections for a while until it became released from the time hold and now it is not in my wallet. Please help thanks.

**Comment by Pyanne** [comment]
Same for me.
Undelegated Luna do not show up in my wallet (I'm using a Ledger Nano S).
I can re-delegate them.

**Comment by 123Grin** [comment]
It is a little confusing but even if you undelegate you cannot withdraw until it is fully vested. Your delegations and undelegatuons show up and your vesting schedule can be seen but it will not show up in your wallet until it is undelegated AND fully vested.

**Comment by terencelimzhengwei** [comment]
@123Grin @Pyanne - understand both of your concerns. We'll see how we can introduce balances that are vesting+undelegated into station.
